name: nodejs
on:
  workflow_dispatch:


jobs:
  node-js:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: 
           repository: PXL-2TIN-DevOps-Resources/calculator-app-finished
      - name: installatie van nodeJs
      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Installatie van dependencies
      - run: npm install

      - name: uitvoering van unit tests
      - run: npm test

      - name: Better Test Reports Action
  # You may pin to the exact commit or the version.
  # uses: mridang/action-test-reporter@720c9c56f73e527681bcb30c33da4ccd62bf70fb
      - uses: mridang/action-test-reporter@v1.3.0
        with:
    # GitHub token used to authenticate API requests. Required for checking status checks and publishing releases. Use `secrets.GITHUB_TOKEN` or a PAT with elevated scopes if needed.
          github-token: 'secrets.GITHUB_TOKEN'
    # The directory where your project is located, used as the base for making file paths in the report relative.
    # The path to the single code coverage report file you want to parse (e.g., 'build/reports/clover.xml').

          coverage-file: true
    # Set to `true` to upload the generated coverage report as a workflow artifact. If omitted or left empty, this defaults to `true`. Set to `false` to disable artifact upload.

          upload-coverage-report: true # optional, default is true
          

      
        
