name: files
on:
  workflow_dispatch:

jobs:
  files:
    runs-on: ubuntu-latest
    steps:
      - run: mkdir lijpe_shit
      - run: echo "penis penis penis" > lijpe_shit/bestand.txt
      - run: ls lijpe_shit
